apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Chart.Name }}-app
  ports:
  - port: 443
    protocol: TCP
    name: https
