apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: istio-ingress-backendconfig
  namespace: istio-system
spec:
  timeoutSec: 60
  connectionDraining:
    drainingTimeoutSec: 90
  cdn:
    enabled: false
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: true
