apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: istio-ingress-backendconfig
  namespace: istio-system
spec:
  timeoutSec: 360
  connectionDraining:
    drainingTimeoutSec: 900
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: true
