apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  name: privacy-proxy-usercentrics-cert
  namespace: istio-system # alongside the ingress object
spec:
  secretName: privacy-proxy-usercentrics-tls
  dnsNames:
  - 'privacy-proxy-server.usercentrics.eu'
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer