apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  name: services-usercentrics-cert
  namespace: istio-system # alongside the ingress object
spec:
  secretName: services-usercentrics-tls
  dnsNames:
    - '*.services.usercentrics.eu'
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer