apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  name: services-<YOUR_DOMAIN>-cert
  namespace: istio-system # alongside the ingress object
spec:
  secretName: services-<YOUR_DOMAIN>-tls
  dnsNames:
    - '*.services.<YOUR_DOMAIN>.eu'
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer