apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  name: tools-<YOUR_DOMAIN>-cert
  namespace: istio-system # alongside the ingress object
spec:
  secretName: tools-<YOUR_DOMAIN>-tls
  dnsNames:
  - '*.tools.<YOUR_DOMAIN>.eu'
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer