apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  name: service-usercentrics-cert
  namespace: istio-system # alongside the ingress object
spec:
  secretName: service-usercentrics-tls
  dnsNames:
  - '*.service.usercentrics.eu'
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer