{
 "title": "Istio Services Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latencies by Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregation": {
      "alignmentPeriod": "stackdriver-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "groupBys": [
       "metric.label.destination_service_name"
      ],
      "perSeriesAligner": "ALIGN_DELTA"
     },
     "filters": [
      "metric.label.response_code",
      "!=",
      "200"
     ],
     "metricKind": "DELTA",
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "stackdriver-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "filters": [
       "metric.label.response_code",
       "!=",
       "200"
      ],
      "groupBys": [
       "metric.label.destination_service_name"
      ],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/server/response_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "staticfilesserver",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     },
     "metricType": "istio.io/service/server/response_latencies",
     "project": { "id": "staticfilesserver", "name": "staticfilesserver" },
     "service": "istio.io",
     "unit": "ms",
     "valueType": "DISTRIBUTION"
    }
   ]
  },
  {
   "title": "Errors by Service",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "aggregation": {
      "alignmentPeriod": "stackdriver-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "groupBys": [
       "metric.label.destination_service_name"
      ],
      "perSeriesAligner": "ALIGN_DELTA"
     },
     "filters": [
      "metric.label.response_code",
      "!=",
      "200"
     ],
     "metricKind": "DELTA",
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "stackdriver-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.label.response_code",
       "!=",
       "200"
      ],
      "groupBys": [
       "metric.label.destination_service_name"
      ],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/server/request_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "staticfilesserver",
      "unit": "1",
      "valueType": "INT64"
     },
     "metricType": "istio.io/service/server/request_count",
     "project": { "id": "staticfilesserver", "name": "staticfilesserver" },
     "service": "istio.io",
     "unit": "1",
     "valueType": "INT64"
    }
   ]
  },
  {
   "title": "Request Rates by Service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "aggregation": {
      "alignmentPeriod": "stackdriver-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "groupBys": [
       "metric.label.destination_service_name"
      ],
      "perSeriesAligner": "ALIGN_DELTA"
     },
     "metricKind": "DELTA",
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "stackdriver-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [
       "metric.label.destination_service_name"
      ],
      "metricKind": "DELTA",
      "metricType": "istio.io/service/server/request_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "staticfilesserver",
      "unit": "1",
      "valueType": "INT64"
     },
     "metricType": "istio.io/service/server/request_count",
     "project": { "id": "staticfilesserver", "name": "staticfilesserver" },
     "service": "istio.io",
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "stackdriver-auto",
      "projectName": "staticfilesserver",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "sloId": ""
     },
     "unit": "1",
     "valueType": "INT64"
    }
   ]
  }
 ]
}