apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  name: tools-<YOUR_DOMAIN>-sandbox-cert
  namespace: istio-system # alongside the ingress object
spec:
  secretName: tools-<YOUR_DOMAIN>-sandbox-tls
  dnsNames:
  - '*.tools.<YOUR_DOMAIN>-sandbox.eu'
  issuerRef:
    name: letsencrypt-issuer-dev
    kind: ClusterIssuer