apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  name: privacy-proxy-usercentrics-sandbox-cert
  namespace: istio-system # alongside the ingress object
spec:
  secretName: privacy-proxy-usercentrics-sandbox-tls
  dnsNames:
  - 'privacy-proxy-server.usercentrics-sandbox.eu'
  issuerRef:
    name: letsencrypt-issuer-dev
    kind: ClusterIssuer