apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: connect-cert
  namespace: confluent
spec:
  commonName: connect
  dnsNames:
    - connect
    - connect.confluent
    - connect.confluent.svc.cluster.local
    - '*.confluent.svc.cluster.local'
    - '*.connect.confluent.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: connect-tls