apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-cert
  namespace: confluent
spec:
  commonName: kafka
  dnsNames:
    - kafka
    - kafka.confluent
    - kafka.confluent.svc.cluster.local
    - '*.confluent.svc.cluster.local'
    - '*.kafka.confluent.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: kafka-tls
