apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kraftcontroller-cert
  namespace: confluent
spec:
  commonName: kraftcontroller
  dnsNames:
    - kraftcontroller
    - kraftcontroller.confluent
    - kraftcontroller.confluent.svc.cluster.local
    - '*.confluent.svc.cluster.local'
    - '*.kraftcontroller.confluent.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: kraftcontroller-tls
