apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-app
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}-app
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-app
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-app
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }} # this value comes from the skaffold.yaml
        envFrom:
          - secretRef:
              name: {{ .Chart.Name }}-secrets
          - configMapRef:
              name: {{ .Chart.Name }}-cgfmap
        ports:
        - containerPort: {{ .Values.containerPort }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
