apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - {{ .Values.domainName }}
  gateways:
  - istio-system/istio-gateway
  http:
  - route:
    - destination:
        host: "{{ .Chart.Name }}-svc.{{ .Values.namespace }}.svc.cluster.local"
        port:
          number: {{ .Values.servicePort }}
      headers:
        response:
          set:
            Strict-Transport-Security: max-age=604800; includeSubDomains