apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    k8s-app: istio
  name: istio-1-6-4-gke-0
  namespace: istio-system
spec:
  addonComponents:
    grafana:
      enabled: true
    kiali:
      enabled: true
    prometheus:
      enabled: true
    tracing:
      enabled: true
  components:
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
      k8s:
        hpaSpec:
          minReplicas: 3
        serviceAnnotations:
          cloud.google.com/neg: '{"ingress": true}'
  revision: istio-164
  values:
    global:
      defaultPodDisruptionBudget:
        enabled: false
      disablePolicyChecks: false
    kiali:
      dashboard:
        auth:
          strategy: token
    grafana:
      accessMode: ReadWriteOnce
      persist: true
      storageClassName: standard
      env:
        GF_AUTH_ANONYMOUS_ENABLED: false
        GF_AUTH_GOOGLE_CLIENT_ID: my_client
        GF_AUTH_GOOGLE_CLIENT_SECRET: my_secret
        GF_AUTH_GOOGLE_ENABLED: true
        GF_AUTH_GOOGLE_ALLOWED_DOMAINS: usercentrics.com
        GF_SERVER_ROOT_URL: https://grafana.tools.usercentrics-sandbox.eu/
    mixer:
      adapters:
        prometheus:
          enabled: false
        useAdapterCRDs: true
    prometheus:
      enabled: false
    telemetry:
      enabled: true
      v1:
        enabled: false
      v2:
        enabled: true
        stackdriver:
          enabled: true