---
- hosts: localhost
  gather_facts: no
  vars:
      gcp_project: usercentrics-playground
      gcp_cred_kind: serviceaccount
      gcp_cred_file: ~/usercentrics-playground-2bbefbe57e2b.json
      gcp_zone: "europe-west1-c"
      gcp_region: "europe-west1"
      gcp_source_image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts"
      gcp_machine_type: "n1-standard-1"
  roles:
    - gce_instance

  tasks:
    - name: Manage new instances
      hosts: new_instances
      connection: ssh
      sudo: True
      roles:
        - base_configuration #TODO: implement
        - production_server  #TODO: implement
