---
- hosts: localhost
  gather_facts: no
  vars:
      gcp_project: <YOUR_DOMAIN>-playground
      gcp_cred_kind: serviceaccount
      gcp_cred_file: ~/<YOUR_DOMAIN>-playground-2bbefbe57e2b.json
      gcp_zone: "europe-west3-a"
      gcp_region: "europe-west3"
      gcp_source_image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts"
      gcp_machine_type: "n1-standard-1"
      gcp_docker_image: "eu.gcr.io/<YOUR_DOMAIN>-playground/helloworld:latest"
  roles:
    - gke_cluster

