---
- name: create a instance group manager
  gcp_compute_instance_group_manager:
    name: crawler-server-app
    base_instance_name: crawler-server-app
    instance_template: "{{ new_instancetemplate }}"
    named_ports:
      - name: http
        port: 80
    target_size: 3
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
