apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: privacy-proxy-<YOUR_DOMAIN>-staging-cert
  namespace: istio-system # alongside the ingress object
spec:
  secretName: privacy-proxy-<YOUR_DOMAIN>-staging-tls
  dnsNames:
  - 'privacy-proxy-server.<YOUR_DOMAIN>-staging.eu'
  issuerRef:
    name: letsencrypt-issuer-stage
    kind: ClusterIssuer