apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: services-<YOUR_DOMAIN>-staging-cert
  namespace: istio-system # alongside the ingress object
spec:
  secretName: services-<YOUR_DOMAIN>-staging-tls
  dnsNames:
  - '*.services.<YOUR_DOMAIN>-staging.eu'
  issuerRef:
    name: letsencrypt-issuer-stage
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: service-<YOUR_DOMAIN>-staging-cert
  namespace: istio-system # alongside the ingress object
spec:
  secretName: service-<YOUR_DOMAIN>-staging-tls
  dnsNames:
  - '*.service.<YOUR_DOMAIN>-staging.eu'
  issuerRef:
    name: letsencrypt-issuer-stage
    kind: ClusterIssuer