apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: privacy-proxy-usercentrics-staging-cert
  namespace: istio-system # alongside the ingress object
spec:
  secretName: privacy-proxy-usercentrics-staging-tls
  dnsNames:
  - 'privacy-proxy-server.usercentrics-staging.eu'
  issuerRef:
    name: letsencrypt-issuer-stage
    kind: ClusterIssuer