apiVersion: cert-manager.io/v1 # changed accordingly to v1.2.0 of cert-manager
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer-stage
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: artem.bogdantsev@usercentrics.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-issuer-stage-account-key
    solvers:
    # ACME DNS-01 provider configurations
    - dns01:
        # Google Cloud DNS
        cloudDNS:
          # The project in which to update the DNS zone
          project: usercentrics-staging
      selector:
        dnsZones:
        - 'usercentrics-staging.eu'