apiVersion: cert-manager.io/v1 # changed accordingly to v1.2.0 of cert-manager
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: ps@<YOUR_DOMAIN>.com
    # Do not create a new ACME account, reuse existing one
    #disableAccountKeyGeneration: true
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    # ACME DNS-01 provider configurations
    - dns01:
        # Google Cloud DNS
        cloudDNS:
          # The project in which to update the DNS zone
          project: staticfilesserver
      selector:
        dnsZones:
        - '<YOUR_DOMAIN>.eu'
